### Get List
GET http://localhost:5000/api/list

### POST List
POST http://localhost:5000/api/list
Content-Type: application/json

{
  "title": "抽獎1"
}

### DELETE List
DELETE http://localhost:5000/api/list/抽獎16

#####################
### GET Prize
GET http://localhost:5000/api/prize

### Get From List
GET http://localhost:5000/api/prize/抽獎1

### POST
POST http://localhost:5000/api/prize
Content-Type: application/json

{
  "name": "c",
  "count": 2,
  "origCount": 2,
  "list_name": "抽獎1"
}

### PATCH
PATCH http://localhost:5000/api/prize/抽獎1
Content-Type: application/json

{
  "name": "c",
  "count": 2,
  "origCount": 2
}

### DELETE
DELETE  http://localhost:5000/api/prize/n3/抽獎1

### DELETE All
DELETE http://localhost:5000/api/prize/all/555

####### Result
### Get result
GET http://localhost:5000/api/result/抽獎1


### POST result
POST http://localhost:5000/api/result/抽獎1
Content-Type: application/json

{
  "name": "b"
}